### PR TITLE
Increment version to 1.5

### PR DESCRIPTION
**Pull request by twomice**
This, plus a corresponding git tag, should trigger a new release on c.o.

### CODE REVIEW

**Comment by twomice** [comment]
@tttp Looking to tag a new release to be listed at https://civicrm.org/extensions/no-overwrite , now that 78f8860f607e5325f062524ea8bd9c0c1b770078 has updated compatibility to include "5.0"

**Comment by tttp** [comment]
I did create a 1.4 with the same aim a few hours ago ;)

I do need to create the tag or can you?

**Comment by twomice** [comment]
Ahah, I didn't even think to check for an existing tag. Your v1.4 tag will work just fine; it includes the 5.0 compatibility, and it should trigger a release on c.o within 24 hours. 

BTW thanks for adding me as a colaborator. I could add the v1.5 tag, but I don't know if we need it.

Of course, now that you've merged info.xml with "version=1.5" I'm not sure what to do. If we create a tag v1.5 it will trigger another new release on c.o, which will be virtually identical to the v1.4 release. 

Your thoughts @tttp ?

**Comment by tttp** [comment]
we haven't had a release in the past 5 years, two in a day is fine, we're
still on a multi year release cycle, it's fine ;)

**Comment by twomice** [comment]
@tttp and @stoob FYI, I found out today that the node at https://civicrm.org/extensions/no-overwrite was not configured for automatic releases based on tags. I've changed that now, so I expect we'll see new releases for v1.4 and v1.5 within the next 24 hours.

**Comment by Stoob** [comment]
It's good for the whole community to keep this valuable extension in the directory.  Thank you @tttp for getting it started @twomice thank you for helping to maintain it.

**Pull request merged**
